### ISSUE TITLE
Not very child-friendly at present

### ISSUE THREAD

**Issue by epbensimpson** [glitchdotcom/friendly-words#27]
We've been looking at the 4-5 character predicates and objects for use in the classroom, so we need to cater for children of all ages and cultures. It strikes me that there are some fairly obvious combinations that could be considered inappropriate, especially ones involving names or other people-related terms.

Small selection:
* `curvy erica`
* `plump amber`
* `cute girl`
* `yummy aunt`
* `drug` is not child-friendly in almost any combination
* `beard clam`
* `ixia` and `ixora` aren't inappropriate but probably not memorable for a child

For now we've given the lists of 4-5 char words to a group of ex-teachers and asked them to flag any combinations they think could be construed as inappropriate or particularly negative. Will be happy to provide a PR once we've trimmed them down.

Edit: Obviously, how "inappropriate" something is is quite subjective, and a lot of users will have a more lax requirement than us... perhaps a flag could be added to indicate which words aren't child-friendly, as opposed to removing them outright? I don't think `tasty drug` is a problematic combination for a internal project or anything, but it's not suitable for kids.

**Comment by lex2491** [comment]
> We've been looking at the 4-5 character predicates and objects for use in the classroom, so we need to cater for children of all ages and cultures. It strikes me that there are some fairly obvious combinations that could be considered inappropriate, especially ones involving names or other people-related terms.
> 
> Small selection:
> 
> * `curvy erica`
> * `plump amber`
> * `cute girl`
> * `yummy aunt`
> * `drug` is not child-friendly in almost any combination
> * `beard clam`
> * `ixia` and `ixora` aren't inappropriate but probably not memorable for a child
> 
> For now we've given the lists of 4-5 char words to a group of ex-teachers and asked them to flag any combinations they think could be construed as inappropriate or particularly negative. Will be happy to provide a PR once we've trimmed them down.
> 
> Edit: Obviously, how "inappropriate" something is is quite subjective, and a lot of users will have a more lax requirement than us... perhaps a flag could be added to indicate which words aren't child-friendly, as opposed to removing them outright? I don't think `tasty drug` is a problematic combination for a internal project or anything, but it's not suitable for kids.

**Comment by jennschiffer** [comment]
Hi! So I merged these changes last week, as we were able to come up with more words to replace them. I still need to publish them to the NPM registry, so I'll keep this issue open until I'm able to do that - the delay is that I got a new work machine and it will take me some set up to be able to publish to NPM again!

**Comment by jennschiffer** [comment]
Okay, I just published, v1.2 is the latest. Thanks again, going to close this now!
