### ISSUE TITLE
Increase Engine Number?

### ISSUE THREAD

**Issue by mcnuttandrew** [glitchdotcom/friendly-words#41]
The current engine number locks this library onto node version 16.x. It appears to run fine on 18.x as well (based on installing it with an --ignore-engines flag). Would it be possible to broaden the engine support to include 18.x? Happy to file a PR to this effect

**Comment by jennschiffer** [comment]
Hi @mcnuttandrew - didn't mean to add that engine last time around, sorry about that. You should be good to go with the newly published 1.2.3!
