### ISSUE TITLE
Teams are not a subset of objects

### ISSUE THREAD

**Issue by myandrienko** [glitchdotcom/friendly-words#42]
README says:

> This is a list of synonyms for "team". They're a special subset of objects.

However out of 130 words for "team" only 39 are also "objects". The rest are not:

```
aerie, alliance, assembly, bale, barrel, batch, bevy, brood, bunch, business, cackle, catch, cauldron, charm, chattering, choir, clan, clattering, clowder, cluster, coalition, combination, committee, company, conglomerate, congregation, conspiracy, convocation, corporation, coven, crew, culture, dazzle, descent, doctrine, drift, drove, exaltation, faction, faculty, fling, flush, gaggle, gathering, gobble, gulp, herd, hive, intrigue, kit, labor, lamentation, league, lease, lineup, murmuration, mustering, ostentation, pace, pack, pandemonium, parliament, phalanx, piteousness, pod, posse, prickle, pride, raffle, romp, rookery, sawt, scoop, scream, scury, sedge, sentence, shiver, shrewdness, sleuth, squad, staff, swarm, troop, troupe, unit, venue, whisp, whiting, wisdom, zeal
```

So either README or "team" words should be updated.

**Comment by cori** [comment]
Hey @myandrienko thanks for writing in!

This factor of the teams words exposes a bit of Glitch's whimsy - many of the words in the list are _collective_ nouns, such as "zeal" and "dazzle", which are [groups of zebras](https://en.wiktionary.org/wiki/zeal).

I've [updated](https://github.com/glitchdotcom/friendly-words/pull/43) the README to be a bit more clear - thanks for the catch!
